name: flutter_app_obrigations
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  http: ^0.13.3 
  google_sign_in: ^6.1.5
  firebase_auth: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7

flutter:
  uses-material-design: true
